# Generated by Django 5.1.4 on 2024-12-17 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Данные Новости',
                'verbose_name_plural': 'Данные Новостей',
            },
        ),
        migrations.CreateModel(
            name='TopicNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_topic', models.CharField(max_length=255, verbose_name='Название темы')),
                ('vote', models.CharField(max_length=255, verbose_name='Голоса за эту тему')),
                ('descript', models.TextField(verbose_name='Описание темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Все возможные темы',
            },
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='Монеты пользователя')),
                ('poll_status', models.JSONField(blank=True, default=list, verbose_name='Массив ключей')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили пользоватей',
            },
        ),
        migrations.CreateModel(
            name='PollInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('POLL', 'Опрос'), ('multi_poll', 'Голосование')], max_length=255, verbose_name='Тип опроса')),
                ('poll_name', models.CharField(max_length=255, verbose_name='Имя опроса')),
                ('vote', models.IntegerField(default=0, verbose_name='Кол-во голосов на данный момент')),
                ('max_vote', models.IntegerField(verbose_name='Кол-во голосов до закрытия опроса')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main_screen.customusermodel', verbose_name='Создатель опроса')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='main_screen.topicnamemodel', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Все возможные опросы',
            },
        ),
    ]
