# Generated by Django 5.1.4 on 2024-12-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Монеты пользователя'),
        ),
        migrations.AlterField(
            model_name='topicnamemodel',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='Голоса за эту тему'),
        ),
    ]
