# Generated by Django 5.1.4 on 2024-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['-date_register'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='listnewsmodel',
            options={'ordering': ['-date'], 'verbose_name': 'Данные Новости', 'verbose_name_plural': 'Данные Новостей'},
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='poll_status',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='poll_status',
            field=models.ManyToManyField(blank=True, related_name='users_accept_poll', to='main_screen.pollinfomodel', verbose_name='Пройденные опросы'),
        ),
    ]
