# Generated by Django 5.2 on 2025-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0003_listnewsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listnewsmodel',
            name='describe',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
